### ISSUE TITLE
Plus d'accès après mise à jour

### ISSUE THREAD

**Issue by piratezen** [299Ko/299ko#32]
Bonjour

J'ai fait la mise à jour automatique de la version 1.2.5 à 1.3. Depuis le site est down avec le message d'erreur : 

Fatal error: Uncaught Error: Class "AltoRouter" not found in /htdocs/common/router/router.php:12 Stack trace: #0 /htdocs/common/common.php(24): include_once() #1 /htdocs/index.php(15): include_once('/htdocs/common/...') #2 {main} thrown in /htdocs/common/router/router.php on line 12

Je suis sous PHP 8.2 avec un hébergement chez LWS.

**Comment by MaxenceCauderlier** [comment]
Bonjour @piratezen 

Est-ce que tu peux poster le contenu du fichier 'data/logs.txt' stp ?
Le fichier 'common/router/AltoRouter.php' existe sur ton site ?

Merci !

**Comment by piratezen** [comment]
J'ai sauvegardé mon site en 1.2.5 et refait une mise à jour. Voici le fichier logs.txt :

[2023-09-27 17:27:37] [INFO] : Begin update to v1.2.1
[2023-09-27 17:27:37] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_beforeChangeFiles.php dont exist
[2023-09-27 17:27:38] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:27:38] [INFO] : ../changelog.md was modified
[2023-09-27 17:27:38] [INFO] : ../common/config.php was modified
[2023-09-27 17:27:38] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:27:39] [INFO] : ../plugin/tinymce/template/admin.css was modified
[2023-09-27 17:27:39] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:27:39] [INFO] : ../theme/default/styles.css was modified
[2023-09-27 17:27:39] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_afterChangeFiles.php dont exist
[2023-09-27 17:27:39] [INFO] : End update to v1.2.1
[2023-09-27 17:27:44] [INFO] : Begin update to v1.2.1
[2023-09-27 17:27:44] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_beforeChangeFiles.php dont exist
[2023-09-27 17:27:44] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:27:44] [INFO] : ../changelog.md was modified
[2023-09-27 17:27:44] [INFO] : ../common/config.php was modified
[2023-09-27 17:27:44] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:27:44] [INFO] : ../plugin/tinymce/template/admin.css was modified
[2023-09-27 17:27:44] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:27:44] [INFO] : ../theme/default/styles.css was modified
[2023-09-27 17:27:44] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_afterChangeFiles.php dont exist
[2023-09-27 17:27:44] [INFO] : End update to v1.2.1
[2023-09-27 17:27:52] [INFO] : Begin update to v1.2.1
[2023-09-27 17:27:52] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_beforeChangeFiles.php dont exist
[2023-09-27 17:27:53] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:27:53] [INFO] : ../changelog.md was modified
[2023-09-27 17:27:53] [INFO] : ../common/config.php was modified
[2023-09-27 17:27:53] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:27:53] [INFO] : ../plugin/tinymce/template/admin.css was modified
[2023-09-27 17:27:53] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:27:53] [INFO] : ../theme/default/styles.css was modified
[2023-09-27 17:27:53] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_afterChangeFiles.php dont exist
[2023-09-27 17:27:53] [INFO] : End update to v1.2.1
[2023-09-27 17:28:03] [INFO] : Begin update to v1.2.1
[2023-09-27 17:28:03] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_beforeChangeFiles.php dont exist
[2023-09-27 17:28:03] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:28:03] [INFO] : ../changelog.md was modified
[2023-09-27 17:28:03] [INFO] : ../common/config.php was modified
[2023-09-27 17:28:03] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:28:03] [INFO] : ../plugin/tinymce/template/admin.css was modified
[2023-09-27 17:28:03] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:28:03] [INFO] : ../theme/default/styles.css was modified
[2023-09-27 17:28:03] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.1/_afterChangeFiles.php dont exist
[2023-09-27 17:28:03] [INFO] : End update to v1.2.1
[2023-09-27 17:28:20] [INFO] : Begin update to v1.2.2
[2023-09-27 17:28:21] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.2/_beforeChangeFiles.php dont exist
[2023-09-27 17:28:21] [INFO] : ../admin/login.php was modified
[2023-09-27 17:28:21] [INFO] : ../admin/lostpwd.php was modified
[2023-09-27 17:28:21] [INFO] : ../admin/scripts.js was modified
[2023-09-27 17:28:22] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:28:22] [INFO] : ../changelog.md was modified
[2023-09-27 17:28:22] [INFO] : ../common/config.php was modified
[2023-09-27 17:28:22] [INFO] : ../plugin/filemanager/admin.php was modified
[2023-09-27 17:28:23] [INFO] : ../plugin/filemanager/lib/FileManager.php was modified
[2023-09-27 17:28:23] [INFO] : ../plugin/filemanager/lib/Folder.php was modified
[2023-09-27 17:28:23] [INFO] : ../plugin/filemanager/param/infos.json was modified
[2023-09-27 17:28:23] [INFO] : ../plugin/filemanager/template/admin.css was modified
[2023-09-27 17:28:24] [INFO] : ../plugin/filemanager/template/listview.php was modified
[2023-09-27 17:28:24] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:28:24] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.2/_afterChangeFiles.php dont exist
[2023-09-27 17:28:24] [INFO] : End update to v1.2.2
[2023-09-27 17:28:46] [INFO] : Begin update to v1.2.2
[2023-09-27 17:28:46] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.2/_beforeChangeFiles.php dont exist
[2023-09-27 17:28:46] [INFO] : ../admin/login.php was modified
[2023-09-27 17:28:46] [INFO] : ../admin/lostpwd.php was modified
[2023-09-27 17:28:46] [INFO] : ../admin/scripts.js was modified
[2023-09-27 17:28:46] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:28:46] [INFO] : ../changelog.md was modified
[2023-09-27 17:28:46] [INFO] : ../common/config.php was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/admin.php was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/lib/FileManager.php was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/lib/Folder.php was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/param/infos.json was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/template/admin.css was modified
[2023-09-27 17:28:46] [INFO] : ../plugin/filemanager/template/listview.php was modified
[2023-09-27 17:28:47] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-27 17:28:47] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.2/_afterChangeFiles.php dont exist
[2023-09-27 17:28:47] [INFO] : End update to v1.2.2
[2023-09-27 17:29:28] [INFO] : Begin update to v1.2.3
[2023-09-27 17:29:28] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.3/_beforeChangeFiles.php dont exist
[2023-09-27 17:29:28] [INFO] : ../admin/scripts.js was modified
[2023-09-27 17:29:28] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:29:29] [INFO] : ../changelog.md was modified
[2023-09-27 17:29:29] [INFO] : ../common/config.php was modified
[2023-09-27 17:29:29] [INFO] : ../plugin/blog/admin.php was modified
[2023-09-27 17:29:30] [INFO] : ../plugin/blog/blog.php was modified
[2023-09-27 17:29:30] [INFO] : ../plugin/blog/param/config.json was modified
[2023-09-27 17:29:30] [INFO] : ../plugin/blog/param/infos.json was modified
[2023-09-27 17:29:30] [INFO] : ../plugin/blog/public.php was modified
[2023-09-27 17:29:31] [INFO] : ../plugin/blog/template/admin.php was modified
[2023-09-27 17:29:31] [INFO] : ../plugin/blog/template/param.php was modified
[2023-09-27 17:29:31] [INFO] : ../plugin/blog/template/public.php was modified
[2023-09-27 17:29:32] [INFO] : ../plugin/filemanager/admin.php was modified
[2023-09-27 17:29:32] [INFO] : ../plugin/filemanager/lib/File.php was modified
[2023-09-27 17:29:32] [INFO] : ../plugin/filemanager/lib/FileManager.php was modified
[2023-09-27 17:29:32] [INFO] : ../plugin/filemanager/lib/Folder.php was modified
[2023-09-27 17:29:33] [INFO] : ../plugin/filemanager/template/listview.php was modified
[2023-09-27 17:29:33] [INFO] : ../plugin/galerie/template/admin.php was modified
[2023-09-27 17:29:33] [INFO] : ../plugin/page/template/admin.php was modified
[2023-09-27 17:29:33] [INFO] : file ../plugin/blog/template/public.css Added
[2023-09-27 17:29:34] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.3/_afterChangeFiles.php dont exist
[2023-09-27 17:29:34] [INFO] : End update to v1.2.3
[2023-09-27 17:30:02] [INFO] : Begin update to v1.2.3
[2023-09-27 17:30:02] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.3/_beforeChangeFiles.php dont exist
[2023-09-27 17:30:02] [INFO] : ../admin/scripts.js was modified
[2023-09-27 17:30:02] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:30:02] [INFO] : ../changelog.md was modified
[2023-09-27 17:30:02] [INFO] : ../common/config.php was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/admin.php was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/blog.php was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/param/config.json was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/param/infos.json was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/public.php was modified
[2023-09-27 17:30:02] [INFO] : ../plugin/blog/template/admin.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/blog/template/param.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/blog/template/public.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/filemanager/admin.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/filemanager/lib/File.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/filemanager/lib/FileManager.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/filemanager/lib/Folder.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/filemanager/template/listview.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/galerie/template/admin.php was modified
[2023-09-27 17:30:03] [INFO] : ../plugin/page/template/admin.php was modified
[2023-09-27 17:30:03] [INFO] : file ../plugin/blog/template/public.css Added
[2023-09-27 17:30:03] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.3/_afterChangeFiles.php dont exist
[2023-09-27 17:30:03] [INFO] : End update to v1.2.3
[2023-09-27 17:30:42] [INFO] : Begin update to v1.2.4
[2023-09-27 17:30:42] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.4/_beforeChangeFiles.php dont exist
[2023-09-27 17:30:42] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:30:43] [INFO] : ../changelog.md was modified
[2023-09-27 17:30:43] [INFO] : ../common/config.php was modified
[2023-09-27 17:30:43] [INFO] : ../common/util.class.php was modified
[2023-09-27 17:30:43] [INFO] : ../plugin/configmanager/admin.php was modified
[2023-09-27 17:30:44] [INFO] : ../plugin/configmanager/configmanager.php was modified
[2023-09-27 17:30:44] [INFO] : ../plugin/configmanager/lib/UpdaterManager.php was modified
[2023-09-27 17:30:44] [INFO] : ../plugin/configmanager/param/hooks.json was modified
[2023-09-27 17:30:44] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:30:45] [INFO] : ../theme/default/styles.css was modified
[2023-09-27 17:30:45] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/299ko/v1.2.4/_afterChangeFiles.php dont exist
[2023-09-27 17:30:45] [INFO] : End update to v1.2.4
[2023-09-27 17:32:18] [INFO] : Nouvelle version trouvée : 1.2.5
[2023-09-27 17:32:25] [INFO] : Begin update to v1.2.5
[2023-09-27 17:32:26] [INFO] : Remote file https://raw.githubusercontent.com/299Ko/versions/main/core/1.2.5/_beforeChangeFiles.php dont exist
[2023-09-27 17:32:26] [INFO] : ../admin/styles.css was modified
[2023-09-27 17:32:26] [INFO] : ../changelog.md was modified
[2023-09-27 17:32:26] [INFO] : ../common/common.php was modified
[2023-09-27 17:32:27] [INFO] : ../common/config.php was modified
[2023-09-27 17:32:27] [INFO] : ../common/core.class.php was modified
[2023-09-27 17:32:27] [INFO] : ../common/show.class.php was modified
[2023-09-27 17:32:27] [INFO] : ../common/util.class.php was modified
[2023-09-27 17:32:28] [INFO] : ../plugin/blog/admin.php was modified
[2023-09-27 17:32:28] [INFO] : ../plugin/blog/blog.php was modified
[2023-09-27 17:32:28] [INFO] : ../plugin/blog/public.php was modified
[2023-09-27 17:32:28] [INFO] : ../plugin/blog/template/admin.php was modified
[2023-09-27 17:32:29] [INFO] : ../plugin/configmanager/admin.php was modified
[2023-09-27 17:32:29] [INFO] : ../plugin/configmanager/param/hooks.json was modified
[2023-09-27 17:32:29] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-27 17:32:29] [INFO] : ../theme/default/header.php was modified
[2023-09-27 17:32:30] [INFO] : file ../plugin/blog/template/admin.css Added
[2023-09-27 17:32:30] [INFO] : Began of _afterChangeFiles
[2023-09-27 17:32:30] [INFO] : Blog Config changed for Author
[2023-09-27 17:32:30] [INFO] : End of _afterChangeFiles
[2023-09-27 17:32:30] [INFO] : End update to v1.2.5
[2023-09-27 17:32:30] [INFO] : Nouvelle version trouvée : 1.2.5
[2023-09-28 10:45:28] [INFO] : Begin update to v1.3.0
[2023-09-28 10:45:28] [INFO] : Began of _beforeChangeFiles
[2023-09-28 10:45:28] [INFO] : End of _beforeChangeFiles
[2023-09-28 10:45:28] [INFO] : ../.gitignore was modified
[2023-09-28 10:45:29] [INFO] : ../admin/header.php was modified
[2023-09-28 10:45:29] [INFO] : ../admin/index.php was modified
[2023-09-28 10:45:29] [INFO] : ../admin/layout.tpl was modified
[2023-09-28 10:45:29] [INFO] : ../admin/login.php was modified
[2023-09-28 10:45:30] [INFO] : ../admin/lostpwd.php was modified
[2023-09-28 10:45:30] [INFO] : ../admin/scripts.js was modified
[2023-09-28 10:45:30] [INFO] : ../admin/styles.css was modified
[2023-09-28 10:45:30] [INFO] : ../changelog.md was modified
[2023-09-28 10:45:31] [INFO] : ../common/administrator.class.php was modified
[2023-09-28 10:45:31] [INFO] : ../common/common.php was modified
[2023-09-28 10:45:31] [INFO] : ../common/config.php was modified
[2023-09-28 10:45:31] [INFO] : ../common/core.class.php was modified
[2023-09-28 10:45:32] [INFO] : ../common/plugin.class.php was modified
[2023-09-28 10:45:32] [INFO] : ../common/pluginsManager.class.php was modified
[2023-09-28 10:45:33] [INFO] : ../common/show.class.php was modified
[2023-09-28 10:45:33] [INFO] : ../common/template.class.php was modified
[2023-09-28 10:45:34] [INFO] : ../common/util.class.php was modified
[2023-09-28 10:45:34] [INFO] : ../index.php was modified
[2023-09-28 10:45:34] [INFO] : ../install.php was modified
[2023-09-28 10:45:34] [INFO] : ../plugin/antispam/admin.php was modified
[2023-09-28 10:45:35] [INFO] : ../plugin/antispam/param/infos.json was modified
[2023-09-28 10:45:35] [INFO] : ../plugin/antispam/template/admin.php was modified
[2023-09-28 10:45:35] [INFO] : ../plugin/blog/admin.php was modified
[2023-09-28 10:45:35] [INFO] : ../plugin/blog/blog.php was modified
[2023-09-28 10:45:36] [INFO] : ../plugin/blog/param/infos.json was modified
[2023-09-28 10:45:36] [INFO] : ../plugin/blog/template/admin.php was modified
[2023-09-28 10:45:36] [INFO] : ../plugin/blog/template/param.php was modified
[2023-09-28 10:45:36] [INFO] : ../plugin/configmanager/admin.php was modified
[2023-09-28 10:45:37] [INFO] : ../plugin/configmanager/configmanager.php was modified
[2023-09-28 10:45:37] [INFO] : ../plugin/configmanager/lib/UpdaterManager.php was modified
[2023-09-28 10:45:37] [INFO] : ../plugin/configmanager/param/infos.json was modified
[2023-09-28 10:45:37] [INFO] : ../plugin/configmanager/template/admin.php was modified
[2023-09-28 10:45:38] [INFO] : ../plugin/contact/admin.php was modified
[2023-09-28 10:45:38] [INFO] : ../plugin/contact/contact.php was modified
[2023-09-28 10:45:38] [INFO] : ../plugin/contact/param/infos.json was modified
[2023-09-28 10:45:38] [INFO] : ../plugin/contact/template/admin.php was modified
[2023-09-28 10:45:39] [INFO] : ../plugin/contact/template/param.php was modified
[2023-09-28 10:45:39] [INFO] : ../plugin/filemanager/admin.php was modified
[2023-09-28 10:45:39] [INFO] : ../plugin/filemanager/filemanager.php was modified
[2023-09-28 10:45:39] [INFO] : ../plugin/filemanager/param/infos.json was modified
[2023-09-28 10:45:40] [INFO] : ../plugin/filemanager/template/listview.php was modified
[2023-09-28 10:45:40] [INFO] : ../plugin/galerie/admin.php was modified
[2023-09-28 10:45:40] [INFO] : ../plugin/galerie/galerie.php was modified
[2023-09-28 10:45:40] [INFO] : ../plugin/galerie/param/infos.json was modified
[2023-09-28 10:45:40] [INFO] : ../plugin/galerie/template/admin.php was modified
[2023-09-28 10:45:41] [INFO] : ../plugin/galerie/template/param.php was modified
[2023-09-28 10:45:41] [INFO] : ../plugin/page/admin.php was modified
[2023-09-28 10:45:41] [INFO] : ../plugin/page/page.php was modified
[2023-09-28 10:45:41] [INFO] : ../plugin/page/param/infos.json was modified
[2023-09-28 10:45:42] [INFO] : ../plugin/page/template/admin.php was modified
[2023-09-28 10:45:42] [INFO] : ../plugin/pluginsmanager/admin.php was modified
[2023-09-28 10:45:42] [INFO] : ../plugin/pluginsmanager/param/infos.json was modified
[2023-09-28 10:45:42] [INFO] : ../plugin/pluginsmanager/template/admin.php was modified
[2023-09-28 10:45:43] [INFO] : ../plugin/seo/admin.php was modified
[2023-09-28 10:45:43] [INFO] : ../plugin/seo/param/config.json was modified
[2023-09-28 10:45:43] [INFO] : ../plugin/seo/param/infos.json was modified
[2023-09-28 10:45:44] [INFO] : ../plugin/seo/seo.php was modified
[2023-09-28 10:45:44] [INFO] : ../plugin/seo/template/admin.php was modified
[2023-09-28 10:45:44] [INFO] : ../plugin/tinymce/param/infos.json was modified
[2023-09-28 10:45:44] [INFO] : ../plugin/tinymce/tinymce.php was modified
[2023-09-28 10:45:45] [INFO] : ../theme/default/404.php was modified
[2023-09-28 10:45:45] [INFO] : ../theme/default/footer.php was modified
[2023-09-28 10:45:45] [INFO] : ../theme/default/header.php was modified
[2023-09-28 10:45:45] [INFO] : ../theme/default/layout.tpl was modified
[2023-09-28 10:45:46] [INFO] : ../theme/default/styles.css was modified
[2023-09-28 10:45:46] [INFO] : file ../.htaccess Added
[2023-09-28 10:45:46] [INFO] : ../common/controllers/ folder has been created
[2023-09-28 10:45:46] [INFO] : file ../common/controllers/Controller.php Added
[2023-09-28 10:45:46] [INFO] : file ../common/controllers/CoreController.php Added
[2023-09-28 10:45:47] [INFO] : file ../common/lang.class.php Added
[2023-09-28 10:45:47] [INFO] : ../common/langs/ folder has been created
[2023-09-28 10:45:47] [INFO] : file ../common/langs/en.ini Added
[2023-09-28 10:45:47] [INFO] : file ../common/langs/fr.ini Added
[2023-09-28 10:45:47] [INFO] : ../common/responses/ folder has been created
[2023-09-28 10:45:47] [INFO] : file ../common/responses/PublicResponse.php Added
[2023-09-28 10:45:48] [INFO] : ../common/router/ folder has been created
[2023-09-28 10:45:48] [INFO] : file ../common/router/AltoRouter.php Added
[2023-09-28 10:45:48] [INFO] : file ../common/router/router.php Added
[2023-09-28 10:45:48] [INFO] : ../plugin/blog/controllers/ folder has been created
[2023-09-28 10:45:48] [INFO] : file ../plugin/blog/controllers/BlogListController.php Added
[2023-09-28 10:45:48] [INFO] : file ../plugin/blog/controllers/BlogReadController.php Added
[2023-09-28 10:45:49] [INFO] : file ../plugin/blog/param/routes.php Added
[2023-09-28 10:45:49] [INFO] : file ../plugin/blog/template/list.tpl Added
[2023-09-28 10:45:49] [INFO] : file ../plugin/blog/template/read.tpl Added
[2023-09-28 10:45:49] [INFO] : ../plugin/contact/controllers/ folder has been created
[2023-09-28 10:45:49] [INFO] : file ../plugin/contact/controllers/ContactController.php Added
[2023-09-28 10:45:49] [INFO] : file ../plugin/contact/param/routes.php Added
[2023-09-28 10:45:50] [INFO] : file ../plugin/contact/template/contact.tpl Added
[2023-09-28 10:45:50] [INFO] : ../plugin/page/controllers/ folder has been created
[2023-09-28 10:45:50] [INFO] : file ../plugin/page/controllers/PageController.php Added
[2023-09-28 10:45:50] [INFO] : file ../plugin/page/param/routes.php Added
[2023-09-28 10:45:51] [INFO] : file ../plugin/page/template/read.tpl Added
[2023-09-28 10:45:51] [INFO] : file ../plugin/blog/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/blog/template/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/contact/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/contact/template/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/page/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/page/template/down.png Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/page/template/public.php Deleted
[2023-09-28 10:45:51] [INFO] : file ../plugin/page/template/up.png Deleted
[2023-09-28 10:45:51] [INFO] : Began of _afterChangeFiles
[2023-09-28 10:45:51] [INFO] : End of _afterChangeFiles
[2023-09-28 10:45:51] [INFO] : End update to v1.3.0


Et voici le nouveau message d'erreur qui apparaît quand j'essaye d'aller sur mon site après la mise à jour en 1.3 :


Fatal error: Uncaught Error: Class "Controller" not found in /htdocs/common/controllers/CoreController.php:12 Stack trace: #0 /htdocs/common/common.php(24): include_once() #1 /htdocs/index.php(15): include_once('/htdocs/common/...') #2 {main} thrown in /htdocs/common/controllers/CoreController.php on line 12

**Comment by MaxenceCauderlier** [comment]
Je ne comprends pas comment ça se fait qu'il ne trouve pas cette classe, puisque visiblement la mise à jour a bien ajouté le fichier qui n'est pas trouvé : 

```
[2023-09-28 10:45:46] [INFO] : file ../common/controllers/Controller.php Added
```

Si tu vas dans le fichier **common/controllers/CoreController**, et que tu le modifies comme ça : 

``` php
defined('ROOT') or exit('No direct script access allowed');
include(COMMON . 'controllers/Controller.php');
class CoreController extends Controller
```

Tu as encore la même erreur ?

**Comment by piratezen** [comment]
Fait et ça remarche. ^^ Merci.

**Comment by MaxenceCauderlier** [comment]
Il faut que je fixe ça ce week-end, avec un moyen propre de charger les classes nécessaires automatiquement, genre avec `spl_autoload`

**Comment by MaxenceCauderlier** [comment]
Fixé ! https://github.com/299Ko/299ko/commit/80e84aa0e8294ed4375094012b616a885bc326ac
